---
- name: Mise en place du hostname
  when: ansible_network_os == 'hp.procurve'
  netmikli:
    host: "{{ ansible_host }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    netmiko_device_type: hp_procurve  

    commands:
      - hostname {{ inventory_hostname }}