---
galaxy_info:
  role_name: backup_cfg
  author: Raphaël LECHAPPE
  description: Ansible role for backing up network equipment configuration 
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: NX-OS
      versions:
        - 5.2(1)N1(4)
  galaxy_tags:
    - backup
    - configuration
    - cisco.nxos.nxos
    - cisco
    - hp
    - NX-OS
    - nx-os 

