- name: Disable password authentification (HP ProCurve)
  netmikli:
    host: "{{ ansible_host }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    port: "{{ ssh_port }}"
    netmiko_device_type: hp_procurve

    commands:
      - aaa authentication ssh login public-key none
      - aaa authentication ssh enable public-key
      - write mem

  register: result
  when: ansible_network_os == 'hp.procurve'
- debug:
    var: result.msg 