---
# This task sets the SNMP community and its group
- name: Setup SNMP community (NX-OS)
  when: ansible_network_os == 'cisco.nxos.nxos'
  cisco.nxos.nxos_snmp_server:
    state: replaced
    config:
      communities:
        - community: Hello
          group: network-operator

- name: Setup SNMP community (HP ProCurve)
  when: ansible_network_os == 'hp.procurve'
  netmikli:
    host: "{{ ansible_host }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    netmiko_device_type: hp_procurve

    commands:
      - snmp-server enable
      - snmp-server community "Hello"
