---
- name: Configure SNMP location (NX-OS)
  when: ansible_network_os == 'cisco.nxos.nxos'
  cisco.nxos.nxos_snmp_server:
    config:
      location: "{{ snmp_location }}"
    state: overridden

- name: Report the /boot/initramfs file status for latest installed kernel
  when: ansible_network_os == 'hp.procurve'
  debug:
    msg: "{{ snmp_location }}"

- name: Configure SNMP location (HP ProCurve)
  when: ansible_network_os == 'hp.procurve'
  netmikli:
    host: "{{ ansible_host }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    netmiko_device_type: hp_procurve

    commands:
      - 'snmp-server location "{{ snmp_location }}"'