---
galaxy_info:
  role_name: feature_setup
  author: Raphaël LECHAPPE
  description: This Ansible role allows you to configure SNMP (Simple Network Management Protocol) on Cisco NX-OS network devices.
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: NX-OS
      versions:
        - 5.2(1)N1(4)
  galaxy_tags:
    - QOS
    - mtu
    - interface
    - configuration
    - cisco.nxos.nxos
    - cisco
    - hp
    - NX-OS
    - nx-os 
