---
# ============================================================== #
# ============================ NX-OS =========================== #
# ============================================================== #
- name: Disable Telnet (NX-OS)
  when: ansible_network_os == 'cisco.nxos.nxos' and features_nxos.disabled is defined
  cisco.nxos.nxos_feature:
    feature: "{{ feature }}"
    state: disabled
  loop: "{{ features_nxos.disabled }}"
  loop_control:
    loop_var: feature

# ============================================================== #
# ========================= HP ProCurve ======================== #
# ============================================================== #