---
# ipfo: true
# grep -r -l 'l2_interfaces' . | xargs sed -i -e 's/l2_interfaces/interfaces/g'
customers:
  - name: Ethernet1/1
    description: "bar 1"
    shutdown: false
    ipfo: true 
  - name: Ethernet1/2
    description: "bar 2"
    shutdown: false
    ipfo: true 
  - name: Ethernet1/3
    description: "bar 3"
    shutdown: true
    ipfo: false 

interfaces:
# ===============================
  - name: Ethernet1/4
    description: "Core: bar"
    shutdown: false
    mode: trunk
    allowed_vlans: "30,40,50"
    speed: 1000
    bpdufilter: true
# ===============================
  - name: Ethernet1/6
    description: "Core: bar"
    shutdown: true
    mode: trunk
    allowed_vlans: "1-2000"
    speed: 10000
# ===============================
  - name: Ethernet1/7
    description: "Core: tar"
    shutdown: false
    mode: trunk
    allowed_vlans: "1-2000"
    speed: 10000
    bpdufilter: true
# ===============================
  - name: Ethernet1/5
    description: "Edge: weeee"
    shutdown: true
    mtu: 9216
    ipv4: "10.1.1.1/24"
    speed: 1000
# ===============================
  - name: Ethernet1/4
    description: "Core: bar"
    shutdown: false
    mode: access
    allowed_vlans: 30
    speed: 1000

port_channels:
# ===============================
  - name: Port-channel10
    description: "Edge: fatal"
    members:
      - member: Ethernet1/8
        mode: active  
      - member: Ethernet1/9
        mode: active  
# ===============================
  - name: Port-channel11
    description: "Edge: fatal"
    members:
      - member: Ethernet1/10
        mode: active
      - member: Ethernet1/11
# ===============================
  - name: Port-channel12
    description: "Edge: fatal"
    members:
      - member: Ethernet1/15
        mode: active
      - member: Ethernet1/16
        mode: active
      - member: Ethernet1/17
        mode: active
      - member: Ethernet1/18
        mode: active
# ===============================

features:
  - vpc
  - hsrp
  - ospf

snmp_location: "Chavanod, France"

STP:
  root: 10-20
  root_secondary: 21-30

vlans:
  - name: Bonus1
    id: 121
  - name: Bonus2
    id: 122
  - name: Bonus3
    id: 123

# l2_interfaces:
# # ===============================
#   - name: Ethernet1/1
#     description: "Core: bar"
#     enable: true
#     mode: trunk
#     allowed_vlans: "30,40,50"
#     speed: 1000
#     bpdufilter: true
# # ===============================
#   - name: Ethernet1/2
#     description: "Core: foo"
#     enable: false
#     mode: access
#     vlan: 10
# # ===============================
#   - name: Ethernet1/3
#     description: "Cust: weweee"
#     enable: true
#     mode: access
#     vlan: 60
# # ===============================
#   - name: Ethernet1/4
#     description: "Edge: brr"
#     enable: true
#     mode: trunk
#     allowed_vlans: "70-80, 90"  
#     speed: 10000
#     bpdufilter: on

# l3_interfaces:
# # ===============================
#   - name: Ethernet1/5
#     description: "Edge: weeee"
#     enable: true
#     mtu: 9216
#     ipv4: "10.1.1.1/24"
#     speed: 1000
# # ===============================
#   - name: Ethernet1/6
#     description: "Edge: biim"
#     enable: true
#     ipv4: "10.1.2.2/24"
#     speed: 10000
# # ===============================
#   - name: Ethernet1/7
#     description: "Edge: fatal"
#     enable: true
#     mtu: 9216
#     ipv4: "10.1.3.3/24"
# # ===============================