---
- name: Configure spanning-tree secondary root bridge (NX-OS)
  when: STP.root_secondary is defined and ansible_network_os == 'cisco.nxos.nxos'
  cisco.nxos.nxos_command:
    commands:
      - configure terminal
      - "spanning-tree vlan {{ STP.root_secondary }} root secondary"

- name: Configure spanning-tree primary root bridge (NX-OS)
  when: STP.root is defined and ansible_network_os == 'cisco.nxos.nxos'
  cisco.nxos.nxos_command:
    commands:
      - configure terminal
      - "spanning-tree vlan {{ STP.root }} root primary"